### ISSUE TITLE
启动报了一个错，很困惑，见日志

### ISSUE THREAD

**Issue by Ankcy** [logex-code/Headline_News_Kotlin_App#1]
[error.log](https://github.com/logex-code/Headline_News_Kotlin_App/files/3211107/error.log)

**Comment by logex-code** [comment]
你是把override fun viewCreate(savedInstanceState: Bundle?)参数的？号去掉了吧 检查下你相关代码有无改动

**Comment by Ankcy** [comment]
> 你是把override fun viewCreate(savedInstanceState: Bundle?)参数的？号去掉了吧 检查下你相关代码有无改动

不去掉之前在android studio3.2里面编译不通过

**Comment by logex-code** [comment]
找到这个viewCreate抽象方法 参数加个允许为空的注解

**Comment by Ankcy** [comment]
> 找到这个viewCreate抽象方法 参数加个允许为空的注解

确实，少了问号，添加后重新编译能运行
初学者，推荐一下学习android java和kotlin的书籍和网站吧，thx!

**Comment by logex-code** [comment]
done
